libbridge: add missing sys/time.h include in header Required to define the 'struct timeval' type:
    In file included from external/bridge-utils/brctl/brctl.c:25:
    external/bridge-utils/brctl/../libbridge/libbridge.h:44:17: error: field has incomplete type 'struct timeval'
            struct timeval max_age;
                           ^

Signed-off-by: Aleksander Morgado <aleksander@aleksander.es>